version: 2 # use CircleCI 2.0.
jobs: # We have jobs key. Each job represents a phase in your Build-Test-Deploy process.

  # ====================================================================================================================
  # Build & deploy on test.
  build:

    # ==================================================================================================================
    # Configuration.
    environment: # Environment.
      TZ: "Europe/Paris" # Set timezone.

    working_directory: ~/loose-touch # directory where steps will run.

    docker: # run the steps with Docker.
      - image: circleci/openjdk:8-jdk-browsers # Java 8 docker image.
        environment: # Environment.
          TZ: "Europe/Paris" # Set timezone.

    # ==================================================================================================================
    # Steps.
    steps: # a collection of executable commands.

      # Get the sources and dependencies.
      - checkout # check out source code to working directory.
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed.
          key: loose-touch-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline # gets the project dependencies.
      - save_cache: # saves the project dependencies.
          paths:
            - ~/.m2
          key: loose-touch-{{ checksum "pom.xml" }}

      # Compile, run tests, package and send the results for reporting.
      - run: mvn clean package
      - store_test_results: # uploads the test metadata directory so that it can show up in the CircleCI dashboard.
          path: api/target/surefire-reports

      # Persist workspace.
      - persist_to_workspace:
          root: ~/loose-touch
          paths: .

  # ====================================================================================================================
  # Deploy on amazon (test).
  deploy_test:

    # ==================================================================================================================
    # Configuration.
    working_directory: ~/loose-touch # directory where steps will run.

    docker: # run the steps with Docker.
      - image: circleci/python:2.7-jessie # Python.

    # ==================================================================================================================
    # Steps.
    steps: # a collection of executable commands.

      # Attach workspace.
      - attach_workspace:
          at: ~/loose-touch

      # Install aws cli & jq.
      - run:
          name: Install awscli & jq
          command: |
            sudo apt-get -yqq update
            sudo apt-get -yqq install jq
            sudo pip install awscli

      # Deploy to aws (test).
      - run: aws cloudformation package --region ${AWS_REGION} --s3-bucket ${AWS_CONFIGURATION_BUCKET} --template-file aws-configuration.yml --output-template-file output-test-aws-configuration.yml
      - run: aws cloudformation deploy --region ${AWS_REGION} --capabilities CAPABILITY_NAMED_IAM --parameter-override Stage=test Prefix=test --template-file output-test-aws-configuration.yml --stack-name loose-touch-test \
      - run: aws s3 sync ./clients/website s3://testloosetouch.com --delete --acl public-read
      - run:
          name: Retrieve aws configuration
          command: |
            export API_URL=`aws cloudformation describe-stacks --stack-name loose-touch-test --region ${AWS_REGION} | jq -r '.Stacks[0].Outputs[] | select(.OutputKey == "APIURL") | .OutputValue'`
            export WWW_URL=`aws cloudformation describe-stacks --stack-name loose-touch-test --region ${AWS_REGION} | jq -r '.Stacks[0].Outputs[] | select(.OutputKey == "WWWURL") | .OutputValue'`
            echo API URL is ${API_URL}
            echo WWW URL is ${WWW_URL}

# ====================================================================================================================
# Loose touch workflow.
workflows:
  version: 2
  build_and_deploy_to_test:
    jobs:
      - build
      - deploy_test:
          requires:
            - build
          filters:
            branches:
              only: development