version: 2 # use CircleCI 2.0
jobs: # We have jobs key. Each job represents a phase in your Build-Test-Deploy process

  # Build job.
  build:

    working_directory: ~/loose-touch # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - run: mvn dependency:go-offline # gets the project dependencies

      - run: mvn package # run the actual tests

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          path: target/surefire-reports