# Reduce logging level to make sure the application works with SAM local
# https://github.com/awslabs/aws-serverless-java-container/issues/134
logging:
  level:
    root: WARN

# Loose touch application configuration.
application:
  jwt:
    secretKey: wM+aATpnGraHYHoEKa2Y4fXANZgffyoey2HPdv4SDzk=
    expirationDelay: 2592000000

# AWS Configuration.
amazon:
  aws:
    accesskey: key
    secretkey: key2
  dynamodb:
    endpoint: http://localhost:8000/

# Spring Security configuration.
security:
  oauth2:
    client:
      clientId: 408314219149-60s8l2ltrbal82hnuj35u81opt27ghsa.apps.googleusercontent.com
      clientSecret: NsR7_eU8KCLZ85BEzske6v_C
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true